import { Property } from "@/types/property";

export const DEMO_PROPERTIES: Property[] = [
  {
    id: "prop_001",
    mlsId: "LAR-241001",
    status: "active",
    listingType: "for_sale",
    price: 1_299_000,
    pricePerSqft: 812,
    daysOnMarket: 8,
    listedDate: "2026-04-16",
    updatedAt: "2026-04-24",
    tags: ["new listing", "move-in ready", "updated kitchen"],
    location: {
      address: "2140 Beachwood Dr",
      city: "Los Angeles",
      state: "CA",
      zip: "90068",
      neighborhood: "Beachwood Canyon",
      lat: 34.1267,
      lng: -118.3281,
    },
    details: {
      beds: 3,
      baths: 2,
      sqft: 1600,
      lotSqft: 5800,
      yearBuilt: 1940,
      propertyType: "single_family",
      parkingSpaces: 2,
      stories: 2,
      garage: true,
    },
    description:
      "Stunning 1940s Spanish Colonial tucked into the Hollywood Hills with sweeping canyon views. Fully renovated kitchen and baths, original hardwood floors, lush terraced garden. Steps from Griffith Park hiking trails. A rare gem below the Hollywood sign.",
    photos: [
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800",
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
    ],
    priceHistory: [
      { date: "2026-04-16", price: 1_299_000, event: "listed" },
    ],
    neighborhoodStats: {
      medianPrice: 1_425_000,
      medianPricePerSqft: 890,
      avgDaysOnMarket: 19,
      totalActiveListing: 12,
      priceChangeYoY: 4.2,
    },
    schoolRating: 8,
    walkScore: 62,
    transitScore: 40,
    bikeScore: 28,
    riskProfile: {
      floodRisk: "minimal",
      fireRisk: "moderate",
      earthquakeRisk: "moderate",
      crimeScore: 32,
    },
    estimatedValue: 1_340_000,
    rentalEstimate: 5_800,
    hoaFee: 0,
    taxRate: 1.12,
    dealScore: {
      total: 82,
      breakdown: {
        valueScore: 85,
        locationScore: 90,
        conditionScore: 88,
        marketMomentumScore: 78,
        riskScore: 65,
      },
      label: "Hot Deal",
      summary:
        "Priced 3% below the neighborhood median with only 8 days on market. The renovated finishes and canyon views justify a premium — this is trading below comparable sales.",
    },
  },
  {
    id: "prop_002",
    mlsId: "LAR-241002",
    status: "active",
    listingType: "for_sale",
    price: 2_150_000,
    pricePerSqft: 1070,
    daysOnMarket: 21,
    listedDate: "2026-04-03",
    updatedAt: "2026-04-24",
    tags: ["rooftop deck", "designer finishes", "smart home"],
    location: {
      address: "820 Nowita Pl",
      city: "Venice",
      state: "CA",
      zip: "90291",
      neighborhood: "Venice",
      lat: 33.9949,
      lng: -118.4534,
    },
    details: {
      beds: 4,
      baths: 3.5,
      sqft: 2010,
      lotSqft: 3200,
      yearBuilt: 2020,
      propertyType: "single_family",
      parkingSpaces: 2,
      stories: 3,
      garage: true,
      pool: false,
    },
    description:
      "Architecturally striking new-build in the heart of Venice. Three floors of curated living with a private rooftop deck showcasing ocean peeks. Designer finishes throughout: Bosch appliances, wide-plank oak floors, Fleetwood pocket doors. Walk to Abbot Kinney in 4 minutes.",
    photos: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
    ],
    priceHistory: [
      { date: "2026-04-03", price: 2_250_000, event: "listed" },
      { date: "2026-04-15", price: 2_150_000, event: "price_change" },
    ],
    neighborhoodStats: {
      medianPrice: 2_075_000,
      medianPricePerSqft: 1030,
      avgDaysOnMarket: 26,
      totalActiveListing: 31,
      priceChangeYoY: 2.1,
    },
    schoolRating: 7,
    walkScore: 91,
    transitScore: 65,
    bikeScore: 88,
    riskProfile: {
      floodRisk: "low",
      fireRisk: "low",
      earthquakeRisk: "moderate",
      crimeScore: 41,
    },
    estimatedValue: 2_090_000,
    rentalEstimate: 9_500,
    hoaFee: 0,
    taxRate: 1.15,
    dealScore: {
      total: 74,
      breakdown: {
        valueScore: 68,
        locationScore: 95,
        conditionScore: 96,
        marketMomentumScore: 72,
        riskScore: 74,
      },
      label: "Good Value",
      summary:
        "Recent price drop brings this closer to comparable sales. The walk score of 91 and Abbot Kinney proximity support strong long-term value. Slightly above estimated AVM — negotiate toward $2.05M.",
    },
  },
  {
    id: "prop_003",
    mlsId: "LAR-241003",
    status: "active",
    listingType: "for_sale",
    price: 875_000,
    pricePerSqft: 700,
    daysOnMarket: 44,
    listedDate: "2026-03-11",
    updatedAt: "2026-04-24",
    tags: ["great schools", "cul-de-sac", "needs work"],
    location: {
      address: "5423 Corteen Pl",
      city: "Valley Village",
      state: "CA",
      zip: "91607",
      neighborhood: "Valley Village",
      lat: 34.1688,
      lng: -118.3966,
    },
    details: {
      beds: 3,
      baths: 2,
      sqft: 1250,
      lotSqft: 6200,
      yearBuilt: 1957,
      propertyType: "single_family",
      parkingSpaces: 2,
      stories: 1,
      garage: true,
    },
    description:
      "Classic mid-century ranch in a quiet cul-de-sac. Solid bones with original character — hardwood floors under carpet, good roof, newer HVAC. Perfect for buyers who want to renovate on their terms. Top-rated Colfax Elementary district.",
    photos: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
      "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800",
    ],
    priceHistory: [
      { date: "2026-03-11", price: 949_000, event: "listed" },
      { date: "2026-03-28", price: 899_000, event: "price_change" },
      { date: "2026-04-10", price: 875_000, event: "price_change" },
    ],
    neighborhoodStats: {
      medianPrice: 915_000,
      medianPricePerSqft: 730,
      avgDaysOnMarket: 22,
      totalActiveListing: 8,
      priceChangeYoY: 5.6,
    },
    schoolRating: 9,
    walkScore: 74,
    transitScore: 58,
    bikeScore: 45,
    riskProfile: {
      floodRisk: "minimal",
      fireRisk: "low",
      earthquakeRisk: "moderate",
      crimeScore: 22,
    },
    estimatedValue: 940_000,
    rentalEstimate: 4_100,
    hoaFee: 0,
    taxRate: 1.08,
    dealScore: {
      total: 79,
      breakdown: {
        valueScore: 88,
        locationScore: 78,
        conditionScore: 60,
        marketMomentumScore: 55,
        riskScore: 88,
      },
      label: "Good Value",
      summary:
        "Three consecutive price cuts over 44 days signal seller motivation. AVM of $940K vs list price of $875K — roughly 7% below estimated value. Strong school district (9/10) and low crime make this a solid long-term play if you can absorb renovation costs.",
    },
  },
  {
    id: "prop_004",
    mlsId: "LAR-241004",
    status: "active",
    listingType: "for_sale",
    price: 4_800_000,
    pricePerSqft: 1600,
    daysOnMarket: 5,
    listedDate: "2026-04-19",
    updatedAt: "2026-04-24",
    tags: ["luxury", "ocean views", "chef's kitchen", "home theater"],
    location: {
      address: "1204 Alta Ave",
      city: "Santa Monica",
      state: "CA",
      zip: "90402",
      neighborhood: "North of Montana",
      lat: 34.0411,
      lng: -118.4985,
    },
    details: {
      beds: 5,
      baths: 5.5,
      sqft: 3000,
      lotSqft: 8500,
      yearBuilt: 2018,
      propertyType: "single_family",
      parkingSpaces: 4,
      stories: 2,
      garage: true,
      pool: true,
    },
    description:
      "One of the most sought-after blocks in Santa Monica. Meticulously crafted transitional home featuring a chef's kitchen with La Cornue range, temperature-controlled wine cellar, saltwater pool, and a dedicated home theater. Primary suite with panoramic ocean and mountain views.",
    photos: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800",
      "https://images.unsplash.com/photo-1600047508788-786f3865b43a?w=800",
      "https://images.unsplash.com/photo-1584738766473-61c083514bf4?w=800",
    ],
    priceHistory: [
      { date: "2026-04-19", price: 4_800_000, event: "listed" },
    ],
    neighborhoodStats: {
      medianPrice: 4_650_000,
      medianPricePerSqft: 1550,
      avgDaysOnMarket: 38,
      totalActiveListing: 7,
      priceChangeYoY: 3.8,
    },
    schoolRating: 10,
    walkScore: 85,
    transitScore: 72,
    bikeScore: 79,
    riskProfile: {
      floodRisk: "low",
      fireRisk: "low",
      earthquakeRisk: "moderate",
      crimeScore: 15,
    },
    estimatedValue: 4_700_000,
    rentalEstimate: 18_000,
    hoaFee: 0,
    taxRate: 1.18,
    dealScore: {
      total: 71,
      breakdown: {
        valueScore: 66,
        locationScore: 98,
        conditionScore: 97,
        marketMomentumScore: 82,
        riskScore: 88,
      },
      label: "Fair Market",
      summary:
        "Priced $100K above current AVM. NOM comps have sold quickly when priced correctly — at $4.8M this may sit. Best-in-class condition and 10/10 school district justify a strong hold. Buyers in this range should target $4.55–4.65M.",
    },
  },
  {
    id: "prop_005",
    mlsId: "LAR-241005",
    status: "active",
    listingType: "for_sale",
    price: 1_575_000,
    pricePerSqft: 875,
    daysOnMarket: 3,
    listedDate: "2026-04-21",
    updatedAt: "2026-04-24",
    tags: ["new listing", "walkable", "Silver Lake", "character home"],
    location: {
      address: "3301 Rowena Ave",
      city: "Los Angeles",
      state: "CA",
      zip: "90027",
      neighborhood: "Silver Lake",
      lat: 34.1077,
      lng: -118.2676,
    },
    details: {
      beds: 3,
      baths: 2,
      sqft: 1800,
      lotSqft: 5000,
      yearBuilt: 1929,
      propertyType: "single_family",
      parkingSpaces: 2,
      stories: 1,
      garage: false,
    },
    description:
      "Rare 1929 Craftsman on Silver Lake's most vibrant street. Light-filled open plan, chef-updated kitchen, serene backyard with koi pond. Walk to Intelligentsia, Whole Foods, Silver Lake Reservoir trails. First time on the market in 18 years.",
    photos: [
      "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800",
      "https://images.unsplash.com/photo-1505843513577-22bb7d21e455?w=800",
    ],
    priceHistory: [
      { date: "2026-04-21", price: 1_575_000, event: "listed" },
    ],
    neighborhoodStats: {
      medianPrice: 1_520_000,
      medianPricePerSqft: 845,
      avgDaysOnMarket: 14,
      totalActiveListing: 18,
      priceChangeYoY: 6.1,
    },
    schoolRating: 8,
    walkScore: 94,
    transitScore: 75,
    bikeScore: 72,
    riskProfile: {
      floodRisk: "minimal",
      fireRisk: "low",
      earthquakeRisk: "moderate",
      crimeScore: 38,
    },
    estimatedValue: 1_610_000,
    rentalEstimate: 6_800,
    hoaFee: 0,
    taxRate: 1.11,
    dealScore: {
      total: 88,
      breakdown: {
        valueScore: 90,
        locationScore: 92,
        conditionScore: 85,
        marketMomentumScore: 90,
        riskScore: 80,
      },
      label: "Hot Deal",
      summary:
        "Only 3 days on market on a street that averages 14. Listed $35K below AVM with walk score of 94 and momentum-driven Silver Lake market up 6.1% YoY. Expect multiple offers — move fast.",
    },
  },
  {
    id: "prop_006",
    mlsId: "LAR-241006",
    status: "active",
    listingType: "for_sale",
    price: 699_000,
    pricePerSqft: 649,
    daysOnMarket: 38,
    listedDate: "2026-03-17",
    updatedAt: "2026-04-24",
    tags: ["condo", "city views", "gym", "doorman"],
    location: {
      address: "1100 Wilshire Blvd #2204",
      city: "Los Angeles",
      state: "CA",
      zip: "90017",
      neighborhood: "Downtown LA",
      lat: 34.0473,
      lng: -118.2598,
    },
    details: {
      beds: 2,
      baths: 2,
      sqft: 1077,
      yearBuilt: 2007,
      propertyType: "condo",
      parkingSpaces: 1,
      stories: 1,
    },
    description:
      "Sophisticated 22nd-floor corner unit with floor-to-ceiling windows and unobstructed downtown views. Full-service luxury high-rise with concierge, rooftop pool, state-of-the-art gym, and private dining room. Steps from Grand Central Market, Crypto.com Arena, and the best of DTLA.",
    photos: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
    ],
    priceHistory: [
      { date: "2026-03-17", price: 749_000, event: "listed" },
      { date: "2026-04-02", price: 719_000, event: "price_change" },
      { date: "2026-04-18", price: 699_000, event: "price_change" },
    ],
    neighborhoodStats: {
      medianPrice: 720_000,
      medianPricePerSqft: 668,
      avgDaysOnMarket: 35,
      totalActiveListing: 47,
      priceChangeYoY: 1.2,
    },
    schoolRating: 6,
    walkScore: 98,
    transitScore: 94,
    bikeScore: 82,
    riskProfile: {
      floodRisk: "minimal",
      fireRisk: "minimal",
      earthquakeRisk: "high",
      crimeScore: 62,
    },
    estimatedValue: 705_000,
    rentalEstimate: 3_200,
    hoaFee: 980,
    taxRate: 1.22,
    dealScore: {
      total: 63,
      breakdown: {
        valueScore: 70,
        locationScore: 88,
        conditionScore: 78,
        marketMomentumScore: 48,
        riskScore: 40,
      },
      label: "Fair Market",
      summary:
        "DTLA condo market is soft — 38 days on market with two price cuts tells the story. High crime score and HOA of $980/month significantly impact carrying cost. Walk score of 98 is exceptional. Right for urban lifestyle buyers, less attractive as investment.",
    },
  },
  {
    id: "prop_007",
    mlsId: "LAR-241007",
    status: "active",
    listingType: "for_sale",
    price: 3_200_000,
    pricePerSqft: 1280,
    daysOnMarket: 11,
    listedDate: "2026-04-13",
    updatedAt: "2026-04-24",
    tags: ["views", "compound", "ADU", "hillside"],
    location: {
      address: "7850 Mulholland Dr",
      city: "Los Angeles",
      state: "CA",
      zip: "90046",
      neighborhood: "Hollywood Hills West",
      lat: 34.1285,
      lng: -118.3936,
    },
    details: {
      beds: 5,
      baths: 4,
      sqft: 2500,
      lotSqft: 14000,
      yearBuilt: 1975,
      propertyType: "single_family",
      parkingSpaces: 4,
      stories: 2,
      garage: true,
      pool: true,
    },
    description:
      "Iconic Mulholland estate with panoramic 270° views stretching from Downtown LA to the Pacific. Gated compound with main house + detached guest suite (ADU). Infinity-edge pool perched on the ridgeline. Fully updated systems with EV charging and solar. The quintessential Hollywood Hills experience.",
    photos: [
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb3?w=800",
      "https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800",
      "https://images.unsplash.com/photo-1614518921816-56ba3bab08b1?w=800",
    ],
    priceHistory: [
      { date: "2026-04-13", price: 3_200_000, event: "listed" },
    ],
    neighborhoodStats: {
      medianPrice: 3_100_000,
      medianPricePerSqft: 1240,
      avgDaysOnMarket: 31,
      totalActiveListing: 14,
      priceChangeYoY: 3.2,
    },
    schoolRating: 7,
    walkScore: 24,
    transitScore: 18,
    bikeScore: 10,
    riskProfile: {
      floodRisk: "minimal",
      fireRisk: "high",
      earthquakeRisk: "moderate",
      crimeScore: 28,
    },
    estimatedValue: 3_190_000,
    rentalEstimate: 14_000,
    hoaFee: 0,
    taxRate: 1.14,
    dealScore: {
      total: 77,
      breakdown: {
        valueScore: 80,
        locationScore: 85,
        conditionScore: 82,
        marketMomentumScore: 75,
        riskScore: 52,
      },
      label: "Good Value",
      summary:
        "Priced in line with AVM at $3.19M. ADU adds meaningful rental offset potential ($3K+/mo). Fire risk is HIGH — critical for insurance costs and resale. For buyers wanting the definitive Hills experience at fair market, this delivers.",
    },
  },
  {
    id: "prop_008",
    mlsId: "LAR-241008",
    status: "active",
    listingType: "for_sale",
    price: 1_099_000,
    pricePerSqft: 785,
    daysOnMarket: 6,
    listedDate: "2026-04-18",
    updatedAt: "2026-04-24",
    tags: ["Culver City", "walkable", "new roof", "updated"],
    location: {
      address: "3874 Jasmine Ave",
      city: "Culver City",
      state: "CA",
      zip: "90232",
      neighborhood: "Culver City",
      lat: 34.0219,
      lng: -118.4024,
    },
    details: {
      beds: 3,
      baths: 2,
      sqft: 1400,
      lotSqft: 5500,
      yearBuilt: 1948,
      propertyType: "single_family",
      parkingSpaces: 2,
      stories: 1,
      garage: true,
    },
    description:
      "Charming post-war bungalow in one of LA's most livable neighborhoods. New roof 2024, updated electrical, recessed lighting throughout. Bright eat-in kitchen, private backyard with mature fruit trees. Walk to Sony Pictures Studios, Culver City dining, and the Expo Line.",
    photos: [
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800",
      "https://images.unsplash.com/photo-1591474200742-8e512e6f98f8?w=800",
    ],
    priceHistory: [
      { date: "2026-04-18", price: 1_099_000, event: "listed" },
    ],
    neighborhoodStats: {
      medianPrice: 1_065_000,
      medianPricePerSqft: 761,
      avgDaysOnMarket: 12,
      totalActiveListing: 14,
      priceChangeYoY: 7.3,
    },
    schoolRating: 9,
    walkScore: 87,
    transitScore: 76,
    bikeScore: 69,
    riskProfile: {
      floodRisk: "minimal",
      fireRisk: "low",
      earthquakeRisk: "moderate",
      crimeScore: 28,
    },
    estimatedValue: 1_120_000,
    rentalEstimate: 4_900,
    hoaFee: 0,
    taxRate: 1.1,
    dealScore: {
      total: 85,
      breakdown: {
        valueScore: 88,
        locationScore: 87,
        conditionScore: 82,
        marketMomentumScore: 88,
        riskScore: 84,
      },
      label: "Hot Deal",
      summary:
        "Listed $21K below AVM in one of LA's fastest-moving markets (12-day average). Culver City is up 7.3% YoY with tech employers anchoring demand. Updated systems reduce near-term capex. Exceptional risk-adjusted value for the westside.",
    },
  },
];

export function getPropertyById(id: string): Property | undefined {
  return DEMO_PROPERTIES.find((p) => p.id === id);
}

export function filterProperties(
  properties: Property[],
  filters: {
    minPrice?: number;
    maxPrice?: number;
    minBeds?: number;
    minBaths?: number;
    propertyTypes?: string[];
    neighborhoods?: string[];
    listingType?: string;
  }
): Property[] {
  return properties.filter((p) => {
    if (filters.minPrice && p.price < filters.minPrice) return false;
    if (filters.maxPrice && p.price > filters.maxPrice) return false;
    if (filters.minBeds && p.details.beds < filters.minBeds) return false;
    if (filters.minBaths && p.details.baths < filters.minBaths) return false;
    if (filters.propertyTypes?.length && !filters.propertyTypes.includes(p.details.propertyType)) return false;
    if (filters.neighborhoods?.length && !filters.neighborhoods.some((n) => p.location.neighborhood.toLowerCase().includes(n.toLowerCase()))) return false;
    if (filters.listingType && p.listingType !== filters.listingType) return false;
    return true;
  });
}
